notifyicon.go
=> notifyicon.go: use existing visibility state when re-adding icon

action.go
Separators were being created with a zero ID, which wasn't a big deal when we weren't reusing IDs, but now that we are, we don't want that (since zero is actually reserved). I added a guard to the allocator to prevent freeing of reserved IDs.
Updates https://github.com/tailscale/corp/issues/8716
=> action.go: guard against freeing of reserved Action IDs

actionlist.go
This patch adds `forEach` and `forEachVisible` as helpers for iterating over an action list, mainly so that `func`s can be passed in that contain `defer` statements.
=> Add convenience methods for iterating over an action list

dpicache/dpicache.go
The dpicache package implements a mapping from a canonical value to equivalent values at specified DPIs. The DPI-specific values are lazily created upon request by calling a CopyForDPI method on the canonical value.
For example, a key could consist of a structure containing UI metrics at 96DPI. Calling InstanceForDPI with that key will return a copy of that structure with metrics that are scaled to the requested DPI.
=> dpicache: add dpicache package

bitmap.go, canvas.go, gdiplus.go
In order to properly support graphics with alpha blending and antialiasing, we need something better than plain old GDI. Given the current state of COM-like bindings, Direct2D is not (yet) an option. GDI+ is a reasonable short-term compromise.
Note that this implementation does not replace Canvas's implementation, as that would likely break compatibility with existing code in a visual sense. Instead, a GDIPlusCanvas may be obtained from a Canvas and operations may then be performed from there.
I did not implement the entire GDI+ API surface, but rather enough to meet Tailscale's needs for painting menus.
The documentation does not delve deeply into nuances of GDI+ semantics, as it seems redundant to me to rewrite Microsoft documentation. Instead, when the semantics of a method are not …
=> flesh out enough GDI+ support for owner-drawn menus

bufferedpaint.go
The buffered paint API takes care of management of back buffers, blitting from the back buffer to the front buffer, and ensuring that the buffer is a top-down DIB, which is needed for alpha blending.
It adds an invocation of BufferedPaintInit on the UI thread to set up a buffer pool that is thread-local.
=> bufferedpaint.go: add support for buffered paint API

font.go
This is a helper that allows us to query LOGFONTs out of a Walk Font. This is necessary for interop with other APIs.
=> font.go: add (*Font).LOGFONTForDPI

rectangle.go, util.go, window.go
Both for scaling between DPIs and converting between win and walk types.
=> add additional helpers for conversions between types

theme.go, window.go
This patch adds bindings for the theme API, and then adds accessors and a cache to Window and WindowBase. The cache is reset whenever setting or theme change messages are received by the WindowBase.
=> theme.go, window.go: add support for the Win32 theme API

form.go, go.mod, go.sum, mainwindow.go, menu.go, notifyicon.go, proceedevent.go, toolbar.go, util.go, window.go
1. We change Menu constructors to set the menu's DwMenuData field to contain a pointer to the Menu itself.
2. We add a resolveMenu function that, given a HMENU, can obtain the DwMenuData field set in (1) and use that to resolve the *Menu.
3. This allows us to be smarter in our window procedures: we add a WM_INITMENUPOPUP to WindowBase which can resolve and dispatch to any Menu. With this code in place, we remove code in window.go, toolbar.go, and mainwindow.go that did the same thing in a more roundabout way.
4. We add initPopupPublisher to Menu which allows the app to receive an event notification when the menu is going to be shown imminently.
5. We rename (*Menu).updateItemsWithImageForWindow to (*Menu).updateItemsForWindow, as future PRs will use that method for more things than just …
=> improvements to menu resolution and notification icons

action.go, menu.go, menuownerdraw.go, menuownerdraw_test.go, window.go
This patch adds support for custom menus, or "owner-draw" in Windows parlance. The idea is that the app includes a handler that implements ActionOwnerDrawHandler to measure and draw the custom content.
To make the menus seemlessly blend into the existing OS theme, we implement much of the theming itself within the framework: checkboxes, highlights, margins, gutters, colors, etc are all handled within walk itself. The app needs only to concern itself with drawing the content area of its menu item.
There are a few gotchas with respect to theming and owner-drawn menus that we need to carefully address with this PR:
* While the Win32 theming API may be considered to be documented, it is done poorly. In particular, while the docs explain all the various constants and metrics that may be …
=> add framework support for owner-drawn menus

bufferedpaint.go, gdiplus.go, menu.go, menuownerdraw.go, proceedevent.go, theme.go
This better reflects the purpose of the variable, which is specific to menus. I also added some missing go:build directives.
=> rename DefaultOwnerDrawHandler to DefaultActionOwnerDrawHandler

gdiplus.go, menuownerdraw.go, menuownerdraw_test.go
Testing has shown that Windows wants the ampersands to be included inside the a11y text. We still need to discover any mnemonic in order to be able to properly respond to it, however we shouldn't strip them.
I also fixed up a couple of typos here and there.
=> menuownerdraw.go: don't strip ampersands out of a11y text

notifyicon.go
This is a known issue that, save for a few old-school Windows hackers, has been lost to the dustbin of history.
When calling TrackPopupMenu(Ex) for notification icons, we need to do a little dance to ensure that focus arrives and leaves the context menu correctly. The original source for this information is long gone, but fortunately I found an archived copy.
See https://web.archive.org/web/20000205130053/http://support.microsoft.com/support/kb/articles/q135/7/88.asp
=> notifyicon.go: post WM_NULL after TrackPopupMenuEx returns

menu.go
As is, this code wastes a bunch of time repeatedly attempting to redraw the menu bar, even if the current menu is a context menu.
We simply add a check to ensure that the current Menu is the main window's top-level menu before issuing the redraw request.
=> menu.go: only redraw the menu bar when the menu represents the menu bar

form.go, menu.go, notifyicon.go, window.go
Walk watches for a notification from Windows when the taskbar is created. The
idea is if Explorer crashes or the walk app starts ahead of Explorer, then
walk will know when it should try re-adding notification icons to the taskbar.
Unfortunately the taskbar also exhibits this behaviour during a change in
the primary display's pixel density. This can happen when an RDP connection is
made, or when the device's monitor configuration changes. In this case,
the Explorer process never terminated, so when we try to re-add our icons,
the Shell_NotifyIcon call fails because the icons are technically still there!
We deal with this nonsense by simply failing out if the Shell_NotifyIcon call
fails; the icon presumably hasn't changed. OTOH, if the call succeeds, we
check the ID against the previous …
=> Improve robustness of (*NotifyIcon).reAddToTaskbar

taskdialog.go
In (*TaskDialogOpts).CommonButtonClicked we were checking the wrong variable. I also added a nil check.
=> taskdialog.go: fix a couple of minor issues

go.mod, go.sum, notifyicon.go
We're going to need a public method for showing a notification icon's context menu. The public version ensures that the desired (x,y) coordinates fall within the notification icon's bounding box.
We also update win and adjust our win.Shell_NotifyIcon callsite accordingly.
Updates https://github.com/tailscale/tailscale/issues/10500
=> go.mod, notifyicon.go: expose (*NotifyIcon).OpenContextMenu

action.go, actionlist.go, declarative/action.go, examples/actions/actions.go, menu.go
This prevents radio button menu items from being unchecked when a user selects an already checked item. It also updates other item states in an exclusivity group when a radio button menu item is checked programmatically or by a user.
Finally, it allows to create radio button menu items using the declarative syntax and updates examples/actions to demonstrate the new behavior.
Fixes #65
=> action.go, menu.go, declarative/action.go, examples/actions: fix radio button menu items

form.go
In 325926d94be67a5b2169e12c178bcc8de2914849 we moved the code from (*FormBase).Run() to (*FormBase).init and removed the former method altogether. This change affected the initialization order of a Window, causing nil pointer dereference errors during MainWindow creation.
This moves the original (*FormBase).Run() code back into its own method and calls it when the form is about to be displayed, ensuring that the window is fully initialized.
Fixes #cleanup
=> form.go: move final initialization to run later in the form's lifecycle

action.go, application.go, widget.go, window.go
I fixed a couple of things that were bothering me in action.go and window.go, but the main thing that is actually a more significant bug is that FormBase's OnPostDispatch was not being invoked as frequently as it was pre-refactor.
There are two reasons for this. The first is that we should call the handler when IsDialogMessage returns true, as that should be treated as as dispatch. Secondly, we also need to handle messages that were dispatched to child windows of the form. In the case of issue 70, the toolbar was receiving a WM_COMMAND whose handler affected layout of the entire form. In that case, we implement OnPostDispatch on WidgetBase and forward it to the Form at the top of the hierarchy.
Fixes #70
=> fix up some post-refactoring issues

theme.go
The syscalls were already implemented in win, but I didn't previously bother to write a nice accessor. Now we have one.
Fixes #74
=> theme.go: add accessor for theme color

window.go
A stupid bug I introduced in a previous commit.
Updates https://github.com/tailscale/corp/issues/23789
=> window.go: do not append nil completion functions when scheduling layout

groupbox.go, layout.go, splitter.go, splitterlayout.go, toolbar.go, window.go
* We get rid of the visible flag in WindowBase; this flag tends to become out of sync with the real state in the window manager. We replace references to it with calls to Visible(), which queries the system instead. Yet another reinforcement of the principle that UI frameworks should not attempt to keep their own copy of window state.
* We set WS_EX_CONTROLPARENT on group box controls.
* We remove control IDs that were being set on the components of GroupBox. Generally group boxes don't need those. I _could_ see an argument for applying an ID to the checkbox that walk supports, however it would need to use the control ID allocator stuff. Since we're not using that, I'm just removing the IDs.
* We fix the CreateWindowEx call for toolbars to include WS_TABSTOP and WS_VISIBLE to bring them …
=> fix layout and visibility issues breaking Taildrop send dialog

dialogex.go, layout.go, pushbutton.go, window.go
I found some more areas inside existing walk code where it is trying to re-implement various dialog manager features that we want to avoid when using DialogEx:
* Form's WM_ACTIVATE handler tries to save and restore the currently focused widget. This competes with the dialog manager, so I added an override in DialogEx to only track the active form.
* I made WM_NEXTDLGCTL use SendMessage whenever possible by flagging when we're handling focus messages and only switching to PostMessage when we risk re-entering. We set that flag in WM_SETFOCUS and WM_KILLFOCUS handlers.
* I prevent layout from forcibly focusing widgets when the enclosing form is a DialogEx; we want that dealt with elsewhere.
* I created overrides for setCtrlID and clearCtrlID in PushButton that also set/clear BS_DEFPUSHBUTTON …
=> more fixes around DialogEx focus handling and default pushbuttons

application.go, gridlayout.go, layout.go
Sometimes when quitting a walk application built in debug mode, I see panics from goroutines that have not finished running by the time the process terminates. While sometimes this doesn't matter, there are other times when we'd like to ensure that goroutines have finished.
I added a new Go method to Application that spawns goroutines that will be associated with a WaitGroup and the Application's Context. (*Application).Run is modified to wait on that WaitGroup before returning.
I also updated layout code to use (*Application).Go instead of directly spawning goroutines.
Fixes #110
=> application.go: Add Go method and WaitGroup to Application

taskdialog.go
This allows an event handler to retain a reference to the dialog's handle for custom manipulations.
Fixes #120
=> taskdialog.go: Change TaskDialog's Created event to supply a Win32Window

taskdialog.go
=> taskdialog.go: Add Destroyed event to TaskDialog

layout.go
=> layout.go: Fix double-close of quit channel

form.go, go.mod, go.sum, notifyicon.go
For Form, we add a new event that is published if EnterMode is called.
For NotifyIcons, we move tracking whether existing context menus are active to handlers for WM_ENTERMENULOOP and WM_EXITMENULOOP, as these messages give us more precise notification as to when menu(s) are present. We also change the tracking variable from a bool to an int, since Win32 APIs to permit nested context menus when specific flags are provided.
We also pick up the latest revision of win.
Updates https://github.com/tailscale/corp/issues/26617
=> form.go, notifyicon.go: Improved tracking of modal loops

taskdialog.go
=> taskdialog.go: ignore CommandLinkMode if a dialog has no custom buttons

notifyicon.go
We handle NIN_KEYSELECT and NIN_SELECT identically to WM_LBUTTONUP.
We initialize the hidden event sink window with WS_DISABLED and annotate it with a window role instead of a client role, in the hope that this will discourage screen readers from focusing on it.
Finally, we do a bit of cleanup since we're already in here.
Updates https://github.com/tailscale/corp/issues/29972
=> notifyicon.go: a11y improvements to notification icons
